# Generated by Django 5.2.4 on 2025-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolesson',
            name='audio_thumbnail',
            field=models.ImageField(default='images/audio_images/default.avif', upload_to='images/audio_images/'),
        ),
    ]
