# Generated by Django 5.2.4 on 2025-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_lessons', '0002_alter_audiolesson_audio_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolesson',
            name='audio_thumbnail',
            field=models.ImageField(default='images/audio_images/default.png', upload_to='images/audio_images/'),
        ),
    ]
